### PR TITLE
Adding english version

### PR DESCRIPTION
**Pull request by 0x8BADFOOD**
This is just for start english version. I don't know Chinese (used google translator).
Partially adapted english.

### CODE REVIEW

**Comment by mzlogin** [comment]
Wow! It's so nice of you to PR this. 👍 👍 👍 

And I'm shocked by your speed, you translate the long doc in just a few hours, how did you do it? 😆

Some people asked me to provide English version after I begin maintained this repository, now I can tell them to enjoy the benefits from you!

Thanks very much!

**Comment by mzlogin** [comment]
Both the quality of translation and typo are not good, but I decide to accept it as a English version base.

I will maintain the English doc with my friends based on your work, welcome to be a reviewer for us.

It seems that you also use Vim, so I want to recommend two plugins to you for edit Markdown files.

* [vim-markdown-toc](https://github.com/mzlogin/vim-markdown-toc)

  A vim plugin wrote by me to generate table of contents for Markdown files. It also can update existing toc, auto update toc on save.

* [vim-table-mode](https://github.com/dhruvasagar/vim-table-mode)

  An awesome automatic table creator & formatter allowing one to create neat tables as you type.

**Comment by 0x8BADFOOD** [comment]
First of all thank you for collecting useful info!
**Sorry for quality.**  I'll try to improve it later.
As for plugins. Yes I saw it but didn't try. I'll check them out.
Thanks.

**Comment by mzlogin** [comment]
Any help for improve this repository is welcome.

**Review by stevenfaelber88-png — APPROVED** [review]

**Pull request merged**
